#!/usr/bin/env python3
"""Write data/<card>/card.json for the 22 major arcana."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

COLORS = {
    "AliceBlue": ("#F0F8FF", "アリスブルー"),
    "AntiqueWhite": ("#FAEBD7", "アンティークホワイト"),
    "Aqua": ("#00FFFF", "アクア"),
    "Aquamarine": ("#7FFFD4", "アクアマリン"),
    "Azure": ("#F0FFFF", "アジュール"),
    "Beige": ("#F5F5DC", "ベージュ"),
    "Bisque": ("#FFE4C4", "ビスク"),
    "Black": ("#000000", "ブラック"),
    "BlanchedAlmond": ("#FFEBCD", "ブランチドアーモンド"),
    "BlueViolet": ("#8A2BE2", "ブルーバイオレット"),
    "Brown": ("#A52A2A", "ブラウン"),
    "BurlyWood": ("#DEB887", "バーリウッド"),
    "Chocolate": ("#D2691E", "チョコレート"),
    "Coral": ("#FF7F50", "コーラル"),
    "CornflowerBlue": ("#6495ED", "コーンフラワーブルー"),
    "Cornsilk": ("#FFF8DC", "コーンシルク"),
    "Crimson": ("#DC143C", "クリムゾン"),
    "DarkGoldenRod": ("#B8860B", "ダークゴールデンロッド"),
    "DarkGreen": ("#006400", "ダークグリーン"),
    "DarkKhaki": ("#BDB76B", "ダークカーキ"),
    "DarkMagenta": ("#8B008B", "ダークマゼンタ"),
    "DarkOliveGreen": ("#556B2F", "ダークオリーブグリーン"),
    "DarkOrange": ("#FF8C00", "ダークオレンジ"),
    "DarkRed": ("#8B0000", "ダークレッド"),
    "DarkSlateBlue": ("#483D8B", "ダークスレートブルー"),
    "DarkSlateGray": ("#2F4F4F", "ダークスレートグレイ"),
    "DeepPink": ("#FF1493", "ディープピンク"),
    "DeepSkyBlue": ("#00BFFF", "ディープスカイブルー"),
    "DimGray": ("#696969", "ディムグレイ"),
    "DodgerBlue": ("#1E90FF", "ドジャーブルー"),
    "FireBrick": ("#B22222", "ファイアブリック"),
    "FloralWhite": ("#FFFAF0", "フローラルホワイト"),
    "ForestGreen": ("#228B22", "フォレストグリーン"),
    "Gainsboro": ("#DCDCDC", "ゲインズボロ"),
    "GhostWhite": ("#F8F8FF", "ゴーストホワイト"),
    "Gold": ("#FFD700", "ゴールド"),
    "GoldenRod": ("#DAA520", "ゴールデンロッド"),
    "Gray": ("#808080", "グレイ"),
    "Green": ("#008000", "グリーン"),
    "HoneyDew": ("#F0FFF0", "ハニーデュー"),
    "HotPink": ("#FF69B4", "ホットピンク"),
    "IndianRed": ("#CD5C5C", "インディアンレッド"),
    "Indigo": ("#4B0082", "インディゴ"),
    "Ivory": ("#FFFFF0", "アイボリー"),
    "Khaki": ("#F0E68C", "カーキ"),
    "Lavender": ("#E6E6FA", "ラベンダー"),
    "LavenderBlush": ("#FFF0F5", "ラベンダーブラッシュ"),
    "LawnGreen": ("#7CFC00", "ローングリーン"),
    "LemonChiffon": ("#FFFACD", "レモンシフォン"),
    "LightBlue": ("#ADD8E6", "ライトブルー"),
    "LightGray": ("#D3D3D3", "ライトグレイ"),
    "LightPink": ("#FFB6C1", "ライトピンク"),
    "LightSlateGray": ("#778899", "ライトスレートグレイ"),
    "LightSteelBlue": ("#B0C4DE", "ライトスティールブルー"),
    "LightYellow": ("#FFFFE0", "ライトイエロー"),
    "Linen": ("#FAF0E6", "リネン"),
    "Maroon": ("#800000", "マルーン"),
    "MediumAquaMarine": ("#66CDAA", "ミディアムアクアマリン"),
    "MidnightBlue": ("#191970", "ミッドナイトブルー"),
    "MintCream": ("#F5FFFA", "ミントクリーム"),
    "MistyRose": ("#FFE4E1", "ミスティローズ"),
    "Moccasin": ("#FFE4B5", "モカシン"),
    "NavajoWhite": ("#FFDEAD", "ナバホホワイト"),
    "Navy": ("#000080", "ネイビー"),
    "OldLace": ("#FDF5E6", "オールドレース"),
    "Olive": ("#808000", "オリーブ"),
    "OliveDrab": ("#6B8E23", "オリーブドラブ"),
    "Orange": ("#FFA500", "オレンジ"),
    "OrangeRed": ("#FF4500", "オレンジレッド"),
    "Orchid": ("#DA70D6", "オーキッド"),
    "PaleTurquoise": ("#AFEEEE", "ペールターコイズ"),
    "PapayaWhip": ("#FFEFD5", "パパイヤホイップ"),
    "PeachPuff": ("#FFDAB9", "ピーチパフ"),
    "Peru": ("#CD853F", "ペルー"),
    "Pink": ("#FFC0CB", "ピンク"),
    "Plum": ("#DDA0DD", "プラム"),
    "PowderBlue": ("#B0E0E6", "パウダーブルー"),
    "Purple": ("#800080", "パープル"),
    "RebeccaPurple": ("#663399", "レベッカパープル"),
    "Red": ("#FF0000", "レッド"),
    "RosyBrown": ("#BC8F8F", "ロージーブラウン"),
    "RoyalBlue": ("#4169E1", "ロイヤルブルー"),
    "SaddleBrown": ("#8B4513", "サドルブラウン"),
    "SandyBrown": ("#F4A460", "サンディブラウン"),
    "SeaGreen": ("#2E8B57", "シーグリーン"),
    "Sienna": ("#A0522D", "シエナ"),
    "Silver": ("#C0C0C0", "シルバー"),
    "SkyBlue": ("#87CEEB", "スカイブルー"),
    "SlateBlue": ("#6A5ACD", "スレートブルー"),
    "SlateGray": ("#708090", "スレートグレイ"),
    "Snow": ("#FFFAFA", "スノー"),
    "SpringGreen": ("#00FF7F", "スプリンググリーン"),
    "SteelBlue": ("#4682B4", "スティールブルー"),
    "Tan": ("#D2B48C", "タン"),
    "Teal": ("#008080", "ティール"),
    "Thistle": ("#D8BFD8", "シスル"),
    "Tomato": ("#FF6347", "トマト"),
    "Turquoise": ("#40E0D0", "ターコイズ"),
    "Violet": ("#EE82EE", "バイオレット"),
    "Wheat": ("#F5DEB3", "ウィート"),
    "White": ("#FFFFFF", "ホワイト"),
    "WhiteSmoke": ("#F5F5F5", "ホワイトスモーク"),
    "Yellow": ("#FFFF00", "イエロー"),
}

CARDS = [
    ("the-fool", "THE FOOL", "愚者", "0",
     ["White", "Snow", "MintCream", "HoneyDew", "SpringGreen", "Azure", "SkyBlue", "LawnGreen", "Cornsilk", "LemonChiffon"],
     ["GhostWhite", "WhiteSmoke", "MistyRose", "SlateGray", "DimGray", "Black", "Maroon", "FireBrick", "Crimson", "Tomato"]),
    ("the-magician", "THE MAGICIAN", "魔術師", "I",
     ["Red", "White", "Gold", "Green", "ForestGreen", "LawnGreen", "Yellow", "Orange", "Silver", "Ivory"],
     ["DarkRed", "Gray", "DimGray", "Black", "DarkSlateGray", "Brown", "SaddleBrown", "Maroon", "Indigo", "Purple"]),
    ("the-high-priestess", "THE HIGH PRIESTESS", "女教皇", "II",
     ["Lavender", "MidnightBlue", "Indigo", "Silver", "AliceBlue", "Plum", "Navy", "GhostWhite", "SlateBlue", "PaleTurquoise"],
     ["DarkSlateBlue", "Purple", "RebeccaPurple", "Thistle", "SlateGray", "Black", "DimGray", "DarkMagenta", "BlueViolet", "LightSlateGray"]),
    ("the-empress", "THE EMPRESS", "女帝", "III",
     ["Wheat", "Cornsilk", "GoldenRod", "ForestGreen", "Olive", "PeachPuff", "PapayaWhip", "Pink", "LavenderBlush", "HoneyDew"],
     ["DarkOliveGreen", "OliveDrab", "RosyBrown", "Sienna", "Khaki", "DarkGoldenRod", "Brown", "Chocolate", "BurlyWood", "Peru"]),
    ("the-emperor", "THE EMPEROR", "皇帝", "IV",
     ["FireBrick", "Crimson", "Red", "Sienna", "SaddleBrown", "SteelBlue", "SlateGray", "Gray", "Silver", "Maroon"],
     ["DarkRed", "Black", "DimGray", "DarkSlateGray", "IndianRed", "Peru", "LightSlateGray", "Brown", "WhiteSmoke", "Snow"]),
    ("the-hierophant", "THE HIEROPHANT", "法王", "V",
     ["Gold", "Ivory", "Linen", "OldLace", "Wheat", "White", "Red", "Purple", "Beige", "FloralWhite"],
     ["AntiqueWhite", "DarkGoldenRod", "Khaki", "SlateGray", "DimGray", "Maroon", "Sienna", "SaddleBrown", "Black", "Tan"]),
    ("the-lovers", "THE LOVERS", "恋人", "VI",
     ["Pink", "LightPink", "LavenderBlush", "Coral", "PeachPuff", "HoneyDew", "Orchid", "Violet", "BlanchedAlmond", "Gold"],
     ["RosyBrown", "Thistle", "Maroon", "MidnightBlue", "DimGray", "DarkRed", "Gray", "Brown", "FireBrick", "Black"]),
    ("the-chariot", "THE CHARIOT", "戦車", "VII",
     ["SteelBlue", "Silver", "Gold", "RoyalBlue", "Navy", "Crimson", "White", "Black", "DodgerBlue", "CornflowerBlue"],
     ["Red", "FireBrick", "OrangeRed", "DarkRed", "Brown", "SaddleBrown", "DimGray", "SlateGray", "DarkSlateGray", "Maroon"]),
    ("strength", "STRENGTH", "力", "VIII",
     ["Gold", "GoldenRod", "Orange", "PeachPuff", "Moccasin", "Linen", "ForestGreen", "Pink", "LemonChiffon", "Wheat"],
     ["Crimson", "Red", "DarkRed", "FireBrick", "Sienna", "DarkGoldenRod", "Brown", "SaddleBrown", "DimGray", "Black"]),
    ("the-hermit", "THE HERMIT", "隠者", "IX",
     ["Gold", "LemonChiffon", "Khaki", "DarkKhaki", "Tan", "BurlyWood", "Sienna", "AntiqueWhite", "NavajoWhite", "Wheat"],
     ["Black", "MidnightBlue", "Navy", "DimGray", "SlateGray", "DarkSlateGray", "Gray", "Snow", "WhiteSmoke", "Brown"]),
    ("wheel-of-fortune", "WHEEL OF FORTUNE", "運命の輪", "X",
     ["Gold", "GoldenRod", "Wheat", "Cornsilk", "SkyBlue", "DeepSkyBlue", "SpringGreen", "Yellow", "Orange", "Azure"],
     ["OliveDrab", "Khaki", "Sienna", "DarkOliveGreen", "Gray", "DimGray", "SlateGray", "Maroon", "Brown", "Black"]),
    ("justice", "JUSTICE", "正義", "XI",
     ["White", "Silver", "SteelBlue", "Gold", "Crimson", "Ivory", "Linen", "RoyalBlue", "Snow", "LightSteelBlue"],
     ["DimGray", "Gray", "Black", "DarkSlateGray", "Maroon", "DarkRed", "SlateGray", "Brown", "FireBrick", "IndianRed"]),
    ("the-hanged-man", "THE HANGED MAN", "吊るされた男", "XII",
     ["ForestGreen", "Olive", "SeaGreen", "Teal", "Silver", "Gold", "SkyBlue", "LightBlue", "Aqua", "MediumAquaMarine"],
     ["DarkGreen", "DarkOliveGreen", "OliveDrab", "Brown", "SaddleBrown", "Sienna", "Gray", "DimGray", "Black", "Maroon"]),
    ("death", "DEATH", "死神", "XIII",
     ["Black", "White", "Snow", "Pink", "Gold", "Orange", "DarkOrange", "Ivory", "FloralWhite", "GhostWhite"],
     ["RosyBrown", "Maroon", "DarkRed", "Brown", "Sienna", "SaddleBrown", "DimGray", "Gray", "SlateGray", "FireBrick"]),
    ("temperance", "TEMPERANCE", "節制", "XIV",
     ["Aqua", "Aquamarine", "MediumAquaMarine", "Turquoise", "PaleTurquoise", "SkyBlue", "Gold", "Wheat", "SeaGreen", "Beige"],
     ["Red", "OrangeRed", "Crimson", "DeepPink", "HotPink", "Chocolate", "Tomato", "Brown", "FireBrick", "Black"]),
    ("the-devil", "THE DEVIL", "悪魔", "XV",
     ["Black", "Maroon", "Gold", "DarkGoldenRod", "SaddleBrown", "FireBrick", "OrangeRed", "Purple", "Indigo", "Chocolate"],
     ["White", "Silver", "LightGray", "Gainsboro", "GhostWhite", "Lavender", "MintCream", "HoneyDew", "Linen", "Ivory"]),
    ("the-tower", "THE TOWER", "塔", "XVI",
     ["Gold", "Yellow", "White", "Red", "OrangeRed", "FireBrick", "Crimson", "Black", "SlateGray", "Gray"],
     ["DarkRed", "Maroon", "Brown", "Sienna", "SaddleBrown", "Khaki", "Tan", "AntiqueWhite", "DimGray", "DarkSlateGray"]),
    ("the-star", "THE STAR", "星", "XVII",
     ["Gold", "Yellow", "LightYellow", "White", "SkyBlue", "Aqua", "Aquamarine", "AliceBlue", "HoneyDew", "CornflowerBlue"],
     ["MidnightBlue", "Navy", "DarkSlateBlue", "DimGray", "SlateGray", "LightSlateGray", "Khaki", "DarkKhaki", "Tan", "Sienna"]),
    ("the-moon", "THE MOON", "月", "XVIII",
     ["Silver", "Lavender", "MidnightBlue", "AliceBlue", "PaleTurquoise", "GhostWhite", "PowderBlue", "SlateBlue", "Wheat", "Linen"],
     ["MistyRose", "WhiteSmoke", "DimGray", "SlateGray", "DarkSlateGray", "LightSlateGray", "DarkSlateBlue", "Indigo", "Black", "Thistle"]),
    ("the-sun", "THE SUN", "太陽", "XIX",
     ["Gold", "GoldenRod", "Orange", "Cornsilk", "Wheat", "Khaki", "DarkKhaki", "Olive", "Sienna", "LemonChiffon"],
     ["Tan", "SandyBrown", "BlanchedAlmond", "Bisque", "FireBrick", "OldLace", "AntiqueWhite", "Moccasin", "BurlyWood", "Peru"]),
    ("judgement", "JUDGEMENT", "審判", "XX",
     ["Gold", "White", "Snow", "Azure", "SkyBlue", "Crimson", "Ivory", "LightYellow", "FloralWhite", "DeepSkyBlue"],
     ["Black", "DimGray", "Gray", "SlateGray", "DarkSlateGray", "Brown", "Sienna", "Khaki", "Maroon", "MidnightBlue"]),
    ("the-world", "THE WORLD", "世界", "XXI",
     ["ForestGreen", "Olive", "Gold", "Purple", "Violet", "Red", "White", "Wheat", "Cornsilk", "SkyBlue"],
     ["OliveDrab", "DarkOliveGreen", "DarkKhaki", "Khaki", "Tan", "Sienna", "Brown", "Gray", "DimGray", "SlateGray"]),
]


def entry(name: str) -> dict:
    hex_value, name_ja = COLORS[name]
    return {"name": name, "hex": hex_value, "nameJa": name_ja}


def main() -> None:
    if len(CARDS) != 22:
        raise SystemExit(f"card count is {len(CARDS)}")
    for card_id, name, name_ja, numeral, upright, reversed_colors in CARDS:
        if len(upright) != 10 or len(reversed_colors) != 10:
            raise SystemExit(f"{card_id}: expected 10 and 10")
        if len(set(upright)) != 10 or len(set(reversed_colors)) != 10:
            raise SystemExit(f"{card_id}: duplicate within an orientation")
        shared = set(upright) & set(reversed_colors)
        if shared:
            raise SystemExit(f"{card_id}: shared colors {shared}")
        payload = {
            "id": card_id,
            "name": name,
            "nameJa": name_ja,
            "numeral": numeral,
            "upright": [entry(color) for color in upright],
            "reversed": [entry(color) for color in reversed_colors],
        }
        path = ROOT / "data" / card_id / "card.json"
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
